--
-- File generated with SQLiteStudio v3.3.3 on quarta nov. 9 18:10:48 2022
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Arbitro
CREATE TABLE Arbitro (id INTEGER PRIMARY KEY REFERENCES Pessoa (id) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: Equipa
CREATE TABLE Equipa (nome VARCHAR PRIMARY KEY, pontuacaoTotal INTEGER DEFAULT (0), golosMarcados INTEGER CONSTRAINT Inicio DEFAULT (0), golosSofridos INTEGER DEFAULT (0), posicao INTEGER DEFAULT (0) CHECK (1 < posicao < 12), diferencaGolos INTEGER GENERATED ALWAYS AS (golosMarcados - golosSofridos), jogosGanhos INTEGER DEFAULT (0), jogosEmpatados INTEGER DEFAULT (0));
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Sporting ', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Electrico FC/CNWF', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('SC Ferreira do Zezere / Stand Amilcareis', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Benfica', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Leoes Porto Salto', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Quinta dos Lombos / ARTIVISION', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('SC Braga / AAUM', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('ADCR Caxinas Poça Barca', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('AD Fundao / Hotel Alambique', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('Portimonense', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('CR Candoso / Natcal', 0, 0, 0, 0, 0, 0);
INSERT INTO Equipa (nome, pontuacaoTotal, golosMarcados, golosSofridos, posicao, jogosGanhos, jogosEmpatados) VALUES ('FC Azemeis by Noxae', 0, 0, 0, 0, 0, 0);

-- Table: Estadio
CREATE TABLE Estadio (id INTEGER PRIMARY KEY, nome VARCHAR, pais VARCHAR, equipa VARCHAR REFERENCES Equipa (nome) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: GoloMarcado
CREATE TABLE GoloMarcado (idGolo INTEGER PRIMARY KEY, minuto INTEGER, idJogador INTEGER REFERENCES Jogador (id) ON DELETE NO ACTION ON UPDATE NO ACTION, idJogo REFERENCES Jogo (id) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: Jogador
CREATE TABLE Jogador (id PRIMARY KEY REFERENCES Pessoa (id), numeroCamisola INTEGER CHECK (1 < numeroCamisola < 99), golosMarcados INTEGER, numeroJogos INTEGER, equipa VARCHAR REFERENCES Equipa (nome) ON DELETE CASCADE ON UPDATE CASCADE);
INSERT INTO Jogador (id, numeroCamisola, golosMarcados, numeroJogos, equipa) VALUES (1, NULL, NULL, NULL, NULL);

-- Table: JogadorJogo
CREATE TABLE JogadorJogo (idJogador REFERENCES Pessoa (id) ON DELETE CASCADE ON UPDATE CASCADE, idJogo REFERENCES Jogo (id) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: Jogo
CREATE TABLE Jogo (id INTEGER PRIMARY KEY, data INTEGER, golosMarcadosVisitante INTEGER, golosMarcadosVisitado INTEGER, resultado VARCHAR, fase VARCHAR, nomeEquipaVisitante VARCHAR REFERENCES Equipa (nome) ON DELETE NO ACTION ON UPDATE NO ACTION, nomeEquipaVisitado VARCHAR REFERENCES Equipa (nome) ON DELETE NO ACTION ON UPDATE NO ACTION, arbitro INTEGER REFERENCES Arbitro (id) ON DELETE CASCADE ON UPDATE CASCADE);

-- Table: Jornada
CREATE TABLE Jornada (numero INTEGER PRIMARY KEY, dataInicio INTEGER, dataFim INTEGER);

-- Table: Pessoa
CREATE TABLE Pessoa (id INTEGER PRIMARY KEY, primeiroNome VARCHAR, segundoNome VARCHAR, idade INTEGER, nacionalidade VARCHAR);
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (1, 'Cammy', 'Stenners', 18, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (2, 'Yule', 'Gwynn', 34, 'Armenia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (3, 'Aloysius', 'Lambertson', 33, 'Japan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (4, 'Burty', 'Salthouse', 32, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (5, 'Reggie', 'McDuffie', 23, 'Sweden');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (6, 'Julie', 'Torrisi', 21, 'Dominican Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (7, 'Edlin', 'Natalie', 36, 'Nigeria');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (8, 'Gilberto', 'Kiddie', 22, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (9, 'Trevar', 'Josifovitz', 38, 'Greece');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (10, 'Salvatore', 'Kinrade', 21, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (11, 'Dene', 'McKevany', 22, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (12, 'Abraham', 'Cruickshanks', 31, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (13, 'Sutton', 'Farge', 37, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (14, 'Jerome', 'Torrejon', 23, 'Togo');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (15, 'Reinald', 'Snawden', 20, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (16, 'Norry', 'Bortolomei', 26, 'Malaysia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (17, 'Seward', 'Cordero', 32, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (18, 'Huey', 'Juschke', 32, 'Argentina');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (19, 'Tyler', 'Sailes', 37, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (20, 'Robby', 'Lowndes', 35, 'Malaysia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (21, 'Aube', 'Cordelet', 39, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (22, 'Clyve', 'Thackwray', 24, 'Belarus');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (23, 'Yancey', 'Shivell', 20, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (24, 'Siffre', 'Hurburt', 25, 'Ukraine');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (25, 'Allistir', 'Domaschke', 19, 'Panama');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (26, 'Nat', 'Symmons', 23, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (27, 'Stinky', 'Ewbanke', 28, 'New Zealand');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (28, 'Tanner', 'Dudden', 19, 'Canada');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (29, 'Fred', 'Blaker', 27, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (30, 'George', 'Jorin', 24, 'Jamaica');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (31, 'Orazio', 'Albery', 18, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (32, 'Samson', 'Lycett', 30, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (33, 'Moise', 'Nilles', 18, 'Republic of the Congo');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (34, 'Trenton', 'Showers', 30, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (35, 'Conan', 'Strewthers', 35, 'Bulgaria');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (36, 'Harbert', 'Aizikov', 34, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (37, 'Vaughan', 'Lally', 33, 'Ukraine');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (38, 'Garald', 'Eitter', 34, 'Thailand');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (39, 'Giacobo', 'Runham', 27, 'Greece');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (40, 'Karlan', 'Pozer', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (41, 'Langsdon', 'Baude', 26, 'Croatia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (42, 'Conrad', 'Ghelardi', 26, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (43, 'Con', 'Mazillius', 17, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (44, 'Durand', 'Piken', 33, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (45, 'Bryanty', 'Cothey', 29, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (46, 'Lev', 'Codling', 39, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (47, 'Ikey', 'Cabera', 35, 'Japan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (48, 'Ferrel', 'Ziehm', 36, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (49, 'Lucais', 'Cracoe', 27, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (50, 'Bran', 'Winfindale', 26, 'Chile');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (51, 'Francklyn', 'Blackborough', 40, 'Tanzania');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (52, 'Alix', 'Vasyushkhin', 26, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (53, 'Ewan', 'Boot', 37, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (54, 'Denny', 'Bullon', 21, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (55, 'Gran', 'Setchfield', 38, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (56, 'Leo', 'Phipson', 34, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (57, 'Mendie', 'Alberti', 31, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (58, 'Courtnay', 'Bolduc', 34, 'Madagascar');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (59, 'Max', 'Boorne', 19, 'Tajikistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (60, 'Tucky', 'Scade', 38, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (61, 'Dante', 'Anthiftle', 22, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (62, 'Fran', 'Neylan', 17, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (63, 'Tybalt', 'Syncke', 27, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (64, 'Colver', 'Alebrooke', 37, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (65, 'Germayne', 'Found', 40, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (66, 'Munroe', 'Getley', 20, 'Senegal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (67, 'Horst', 'Hrinishin', 31, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (68, 'Ailbert', 'Markson', 35, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (69, 'Nobie', 'Duddin', 19, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (70, 'Jay', 'Boord', 26, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (71, 'Ange', 'Tregensoe', 19, 'Netherlands');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (72, 'Karney', 'Dossettor', 20, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (73, 'Quincy', 'Robus', 32, 'Thailand');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (74, 'Gan', 'Blazey', 24, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (75, 'Daron', 'Buckel', 33, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (76, 'Flory', 'Perrett', 20, 'Azerbaijan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (77, 'Reggie', 'Tokley', 36, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (78, 'Marty', 'Emlyn', 19, 'Netherlands');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (79, 'Cobb', 'Duley', 25, 'Canada');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (80, 'Kristopher', 'Stood', 21, 'Serbia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (81, 'Paddie', 'Coumbe', 18, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (82, 'Payton', 'Dodd', 27, 'South Africa');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (83, 'Pablo', 'Kinge', 32, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (84, 'Marsh', 'Ledes', 22, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (85, 'Lawrence', 'Perfitt', 23, 'Tanzania');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (86, 'Bronson', 'Saladine', 37, 'Malta');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (87, 'Jerrie', 'Orteaux', 30, 'Slovenia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (88, 'Stillmann', 'Parres', 30, 'North Korea');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (89, 'Cosimo', 'Wolters', 20, 'Guatemala');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (90, 'Zeb', 'Plews', 18, 'Jamaica');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (91, 'Peyter', 'Dyche', 35, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (92, 'Wallis', 'Marchington', 20, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (93, 'Arnold', 'Pheasey', 39, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (94, 'Rogers', 'Snoxell', 19, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (95, 'Waylin', 'Duce', 34, 'Croatia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (96, 'Cristobal', 'Memmory', 22, 'Vietnam');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (97, 'Saw', 'Boig', 30, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (98, 'Tedie', 'Poxson', 22, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (99, 'Gibb', 'Lode', 34, 'Peru');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (100, 'Augy', 'Pedden', 37, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (101, 'Gustav', 'Tedstone', 27, 'American Samoa');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (102, 'Artemus', 'Trevna', 37, 'Vietnam');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (103, 'Cheston', 'Longo', 28, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (104, 'Wait', 'Meaney', 22, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (105, 'Constantin', 'Pingstone', 37, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (106, 'Garold', 'Jablonski', 17, 'Dominican Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (107, 'Bertrando', 'De Ambrosis', 27, 'Turkmenistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (108, 'Nestor', 'Pyson', 34, 'Norway');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (109, 'Pace', 'Hovie', 26, 'Bulgaria');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (110, 'Alon', 'Gilbank', 40, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (111, 'Husein', 'Adamovich', 19, 'Thailand');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (112, 'Abbot', 'Tween', 19, 'Pakistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (113, 'Abrahan', 'Roof', 30, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (114, 'Cirillo', 'Seckom', 33, 'Belarus');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (115, 'Wolfie', 'Sommerfeld', 38, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (116, 'Thorpe', 'Goult', 28, 'Tunisia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (117, 'Robinson', 'Flecknell', 30, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (118, 'Kenn', 'Pilley', 23, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (119, 'Sigismundo', 'Woodhall', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (120, 'Fraser', 'Dillamore', 27, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (121, 'Lucien', 'Gidney', 26, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (122, 'Reube', 'Noe', 18, 'Canada');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (123, 'Mackenzie', 'Abdie', 17, 'Peru');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (124, 'Chan', 'Wolffers', 34, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (125, 'Nero', 'Blethyn', 33, 'Hungary');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (126, 'Francklin', 'Hartfleet', 34, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (127, 'Farris', 'Minear', 30, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (128, 'Spike', 'Challens', 31, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (129, 'Egbert', 'Playle', 24, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (130, 'Milo', 'Dibley', 34, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (131, 'Julius', 'Trodd', 22, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (132, 'Esme', 'Burcher', 19, 'Guatemala');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (133, 'Abner', 'Newlands', 39, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (134, 'Joshuah', 'Rantoul', 30, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (135, 'Hebert', 'Rabl', 20, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (136, 'Shell', 'Outibridge', 40, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (137, 'Jervis', 'Hexam', 22, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (138, 'Reuven', 'D''eye', 38, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (139, 'Alistair', 'Dmitrienko', 25, 'Hong Kong');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (140, 'Emmy', 'Cressy', 20, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (141, 'Klemens', 'Rodinger', 24, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (142, 'Mohammed', 'Stolworthy', 18, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (143, 'Dimitry', 'Vlasyuk', 40, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (144, 'Chrisse', 'Aslam', 28, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (145, 'Hamlin', 'McManus', 18, 'Sweden');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (146, 'Kinnie', 'Vanshin', 26, 'Yemen');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (147, 'Wang', 'Pedersen', 35, 'Iran');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (148, 'Duane', 'Dowsing', 40, 'Norway');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (149, 'Aharon', 'Gerbel', 25, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (150, 'Adolphe', 'Markson', 40, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (151, 'Westleigh', 'Wildor', 25, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (152, 'Rafael', 'Labrone', 34, 'Ukraine');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (153, 'Creighton', 'Deighan', 21, 'Nicaragua');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (154, 'Derrik', 'Pamplin', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (155, 'Dur', 'Mechem', 25, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (156, 'Arvy', 'Haps', 20, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (157, 'Odell', 'Coultard', 30, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (158, 'Welby', 'Lackey', 26, 'Mauritius');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (159, 'Lombard', 'Friedman', 26, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (160, 'Thom', 'Peplaw', 31, 'Norway');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (161, 'Darnall', 'Sloat', 25, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (162, 'Traver', 'Whiteford', 29, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (163, 'Penny', 'Carl', 26, 'Antigua and Barbuda');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (164, 'Vinson', 'Danson', 34, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (165, 'Vin', 'Mayers', 33, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (166, 'Theodore', 'Bentje', 36, 'Panama');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (167, 'Gil', 'Balnaves', 18, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (168, 'Jeremie', 'Wapples', 26, 'Greece');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (169, 'Benjy', 'Moresby', 17, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (170, 'Granger', 'Aubury', 32, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (171, 'Herve', 'Kepling', 29, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (172, 'Karoly', 'Nowick', 31, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (173, 'Alphonso', 'Russan', 39, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (174, 'Pincas', 'Crafts', 37, 'Greece');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (175, 'Pall', 'Mellon', 22, 'Niger');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (176, 'Wolfy', 'Di Biagio', 28, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (177, 'Sinclare', 'Newick', 35, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (178, 'Delbert', 'Durtnall', 25, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (179, 'Domingo', 'Burbury', 37, 'Andorra');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (180, 'Delmar', 'Barsam', 19, 'Sri Lanka');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (181, 'Jarad', 'Copin', 37, 'Malaysia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (182, 'Jeramey', 'Burgyn', 21, 'French Polynesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (183, 'Sylas', 'Jirasek', 29, 'Mexico');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (184, 'Rickert', 'Botright', 21, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (185, 'Elliot', 'Beazey', 19, 'Cuba');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (186, 'Armand', 'Bradshaw', 21, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (187, 'Lonnie', 'Shekle', 39, 'Mali');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (188, 'Vinnie', 'Vanyarkin', 35, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (189, 'Goraud', 'Cornock', 21, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (190, 'Abdel', 'Mallebone', 34, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (191, 'Lothario', 'Matteoni', 35, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (192, 'Prince', 'Woollin', 25, 'Nigeria');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (193, 'Jeremie', 'Rogeon', 28, 'Argentina');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (194, 'Haroun', 'Lathbury', 38, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (195, 'Averill', 'Leming', 28, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (196, 'Baron', 'Flag', 36, 'India');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (197, 'Creigh', 'Minget', 26, 'Japan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (198, 'Lewie', 'Goldberg', 26, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (199, 'Hamish', 'Mansel', 39, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (200, 'Salem', 'Tames', 36, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (201, 'Dolf', 'Songust', 19, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (202, 'Massimo', 'Nuzzetti', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (203, 'Isidor', 'Keeling', 20, 'Haiti');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (204, 'Mata', 'Ionesco', 27, 'Afghanistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (205, 'Clair', 'McGillicuddy', 28, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (206, 'Osgood', 'Carnow', 19, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (207, 'Frederico', 'Aveson', 24, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (208, 'Roley', 'Ivamy', 39, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (209, 'Koenraad', 'Lodemann', 34, 'Chile');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (210, 'Darill', 'Gookey', 28, 'Luxembourg');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (211, 'Jabez', 'Bimson', 23, 'Afghanistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (212, 'Fergus', 'Norcock', 35, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (213, 'Cal', 'De Bell', 29, 'Japan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (214, 'Obie', 'Coning', 25, 'Pakistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (215, 'Gabby', 'Depport', 21, 'Spain');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (216, 'Silvester', 'Mathews', 17, 'Slovenia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (217, 'Sascha', 'Boylan', 29, 'France');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (218, 'Shannon', 'Moir', 34, 'Taiwan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (219, 'Prescott', 'Caudray', 39, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (220, 'Ludvig', 'Epp', 19, 'Italy');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (221, 'Fielding', 'Itter', 29, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (222, 'Artemas', 'Shekle', 26, 'Thailand');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (223, 'Bert', 'Zotto', 35, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (224, 'Guss', 'O''Shaughnessy', 30, 'Namibia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (225, 'Matteo', 'Gilbart', 24, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (226, 'Purcell', 'Pharoah', 18, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (227, 'Even', 'Ewen', 40, 'Iran');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (228, 'Duncan', 'Bentke', 23, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (229, 'Ellary', 'Malpas', 36, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (230, 'Shalom', 'Florentine', 20, 'Chile');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (231, 'Kalvin', 'Guerro', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (232, 'Augusto', 'Boate', 33, 'Colombia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (233, 'Nickie', 'Birkhead', 28, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (234, 'Giffard', 'Hrachovec', 34, 'Sweden');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (235, 'Worthy', 'Narramore', 20, 'Palestinian Territory');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (236, 'Alfie', 'Jackalin', 37, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (237, 'Hobey', 'Stillwell', 29, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (238, 'Lewes', 'Reoch', 25, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (239, 'Erl', 'Meininking', 25, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (240, 'Tymon', 'Blowin', 23, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (241, 'Huey', 'Von Oertzen', 29, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (242, 'Fredek', 'Nouch', 40, 'Pakistan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (243, 'Hillery', 'Amoore', 22, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (244, 'Huntington', 'Rosenschein', 36, 'Ukraine');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (245, 'Jonah', 'Stalley', 32, 'Samoa');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (246, 'Hilly', 'Taks', 21, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (247, 'Brit', 'Collin', 18, 'Ukraine');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (248, 'Ewell', 'Bigrigg', 19, 'Slovenia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (249, 'Claudell', 'Conniam', 34, 'Panama');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (250, 'Delmore', 'Trevithick', 18, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (251, 'Giordano', 'Rendle', 20, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (252, 'Clementius', 'O''Bradain', 36, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (253, 'Cleavland', 'Paggitt', 26, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (254, 'Arnie', 'Bucklan', 17, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (255, 'Christophorus', 'Linzee', 22, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (256, 'Kip', 'Shearsby', 40, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (257, 'Waldon', 'Overell', 20, 'Venezuela');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (258, 'Gearard', 'Cisneros', 34, 'Portugal');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (259, 'Scott', 'O''Corrigane', 35, 'Honduras');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (260, 'Wendel', 'Beech', 33, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (261, 'Skell', 'Davidoff', 25, 'Russia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (262, 'Ermanno', 'Tromans', 35, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (263, 'Bron', 'Bassill', 21, 'Greece');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (264, 'Abdul', 'Channer', 35, 'Bosnia and Herzegovina');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (265, 'Richmound', 'Kinchin', 39, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (266, 'Roley', 'Avory', 30, 'Philippines');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (267, 'Pauly', 'Bhar', 36, 'Canada');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (268, 'Munroe', 'Sigfrid', 29, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (269, 'Giorgi', 'Julian', 32, 'Nigeria');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (270, 'Alvie', 'Kondratyuk', 33, 'Malta');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (271, 'Lyon', 'Emmanueli', 26, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (272, 'Reinald', 'Huntington', 23, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (273, 'Tate', 'Runnacles', 32, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (274, 'Claudianus', 'Fitzsimmons', 32, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (275, 'Ives', 'Pawelski', 23, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (276, 'Padraig', 'Townley', 32, 'Vietnam');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (277, 'Rip', 'Boughton', 19, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (278, 'Terencio', 'Cockton', 19, 'New Caledonia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (279, 'Bryanty', 'Thurske', 17, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (280, 'Orville', 'Gresswell', 28, 'United States');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (281, 'Monro', 'Regglar', 28, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (282, 'Silvano', 'Micklewicz', 20, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (283, 'Hewe', 'McDowall', 32, 'Peru');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (284, 'Cedric', 'Boost', 31, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (285, 'Christiano', 'Roderighi', 18, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (286, 'Georges', 'Verissimo', 23, 'Czech Republic');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (287, 'Barde', 'Chipping', 17, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (288, 'Efrem', 'Carver', 23, 'Egypt');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (289, 'Haydon', 'Brayfield', 27, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (290, 'Chaddie', 'Gideon', 19, 'Japan');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (291, 'Caesar', 'Flowers', 31, 'Guatemala');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (292, 'Costa', 'McGeachey', 17, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (293, 'Cob', 'Pastor', 27, 'Brazil');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (294, 'Noach', 'Huckle', 31, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (295, 'Elden', 'Blackbrough', 17, 'Indonesia');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (296, 'Murdock', 'Matussevich', 26, 'China');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (297, 'Haley', 'Gowers', 36, 'Poland');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (298, 'Rustie', 'Bodicam', 32, 'Israel');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (299, 'Dickie', 'Bertholin', 33, 'Venezuela');
INSERT INTO Pessoa (id, primeiroNome, segundoNome, idade, nacionalidade) VALUES (300, 'Titos', 'Feron', 34, 'Portugal');

-- Table: Treinador
CREATE TABLE Treinador (id INTEGER PRIMARY KEY REFERENCES Pessoa (id) ON DELETE CASCADE ON UPDATE CASCADE, equipa REFERENCES Equipa (nome) ON DELETE CASCADE ON UPDATE CASCADE);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
